# 0.0 is the only allowed value
# See https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure.html
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/{{ project_name }}

permissions:
  - object: /var/www/{{ project_name }}/manage.py
    mode: 755
  - object: /var/www/{{ project_name }}/scripts
    pattern: "**"
    type:
      - file
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/codedeploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/codedeploy/validate_service.sh
      timeout: 300
      runas: root

